version: "3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.5.4"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.5.4"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
  apm-server:
    image: "docker.elastic.co/apm/apm-server:6.5.4"
    ports:
      - "8200:8200"


